#!/bin/bash
# Gate Validation Script
# Functional tests for all backend APIs

BASE_URL="http://localhost:8001"

echo "=== GATE B1: FILE OPERATIONS ==="
echo ""
echo "1. Service methods implemented:"
grep -c "def " claude_code_api/services/file_operations.py
echo ""
echo "2. API endpoints count:"
grep -c "@router" claude_code_api/api/files.py
echo ""
echo "3-4. List /tmp:"
curl -s "${BASE_URL}/v1/files/list?path=/tmp" | python3 -c "import sys,json; print(len(json.load(sys.stdin)))"
echo ""
echo "5. Read file:"
curl -s "${BASE_URL}/v1/files/read?path=/tmp/api-test.txt" | python3 -c "import sys,json; print(json.load(sys.stdin)['content'][:50])"
echo ""
echo "6. Write file:"
curl -s -X POST "${BASE_URL}/v1/files/write" -H 'Content-Type: application/json' -d '{"path":"/tmp/validation.txt","content":"Test"}' | python3 -c "import sys,json; print(json.load(sys.stdin)['name'])"
test -f /tmp/validation.txt && echo "  ✅ Verified on filesystem" || echo "  ❌ NOT on filesystem"
echo ""
echo "7. Search:"
curl -s "${BASE_URL}/v1/files/search?root=/tmp&query=validation" | python3 -c "import sys,json; print(len(json.load(sys.stdin)))"
echo ""
echo "8. Security:"
curl -s "${BASE_URL}/v1/files/read?path=/etc/passwd" 2>&1 | grep -q "not in allowed" && echo "  ✅ PASS: Traversal blocked" || echo "  ❌ FAIL"
echo ""
echo "9. HTTP codes:"
CODE=$(curl -s -o /dev/null -w '%{http_code}' "${BASE_URL}/v1/files/read?path=/tmp/missing.txt")
echo "  404 for missing: $CODE"
echo ""
echo "10. Project discovery:"
curl -s "${BASE_URL}/v1/host/discover-projects?scan_path=/Users/nick/Desktop/claude-mobile-expo" | python3 -c "import sys,json; d=json.load(sys.stdin); print(d[0]['name'] if d else 'None')"
echo ""
echo "=== GATE B2: GIT OPERATIONS ==="
echo ""
echo "1. Git status:"
curl -s "${BASE_URL}/v1/git/status?project_path=/Users/nick/Desktop/claude-mobile-expo" | python3 -c "import sys,json; d=json.load(sys.stdin); print(f\"Branch: {d['current_branch']}, Modified: {len(d['modified'])}\")"
echo ""
echo "2. Git log:"
curl -s "${BASE_URL}/v1/git/log?project_path=/Users/nick/Desktop/claude-mobile-expo&max=1" | python3 -c "import sys,json; d=json.load(sys.stdin); print(d[0]['short_sha'] if d else 'None')"
echo ""
echo "3. Create commit:"
curl -s -X POST "${BASE_URL}/v1/git/commit" -H 'Content-Type: application/json' -d "{\"project_path\":\"/Users/nick/Desktop/claude-mobile-expo\",\"message\":\"test: gate validation commit\"}" | python3 -c "import sys,json; d=json.load(sys.stdin); print(d.get('short_sha', d.get('detail', 'Error')))"
echo ""
echo "4. Branches:"
curl -s "${BASE_URL}/v1/git/branches?project_path=/Users/nick/Desktop/claude-mobile-expo" | python3 -c "import sys,json; print(len(json.load(sys.stdin)))"
echo ""
echo "=== GATE B3: MCP MANAGEMENT ==="
echo ""
echo "1. List MCPs:"
curl -s "${BASE_URL}/v1/mcp/servers" | python3 -c "import sys,json; print(len(json.load(sys.stdin)))"
echo ""
echo "2. Add MCP:"
curl -s -X POST "${BASE_URL}/v1/mcp/servers" -H 'Content-Type: application/json' -d '{"name":"test","url":"http://test","api_key":"key123"}' | python3 -c "import sys,json; print(json.load(sys.stdin).get('name', 'Error'))"
echo ""
echo "3. List after add:"
curl -s "${BASE_URL}/v1/mcp/servers" | python3 -c "import sys,json; print(len(json.load(sys.stdin)))"
echo ""
echo "4. Remove MCP:"
curl -s -X DELETE "${BASE_URL}/v1/mcp/servers/test" | python3 -c "import sys,json; print(json.load(sys.stdin).get('success', False))"
echo ""
echo "=== ALL GATES SUMMARY ==="
echo "Run complete. Review results above."
